lab12/cs251project/django/feeder/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^', include('website.urls', namespace='website')),
]

lab12/cs251project/django/website/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.http import HttpResponse

from . import views

from django.conf.urls import handler404

urlpatterns = [
    ## Registeration and Signin
    url(r'^$', views.signin, name='signin'),
    url(r'^signup$', views.signup, name='signup'),  # for registering new users
    url(r'^signout$', views.signout, name='signout'),
    url(r'^complete-reg$', views.completeReg, name='complete-reg'),
    url(r'^complete-signup$',views.complete_signup,name="complete_signup"),

    ## robots.txt
    url(r'^robots.txt$', lambda r: HttpResponse("User-agent: *\nDisallow: /", content_type="text/plain")),

    ## View and register Students
    ## Only for Admin :(
    url(r'^students/view$', views.view_students, name="view_students"),
    url(r'^students/add$', views.add_students, name="add_students"),

    ## home sweet home
    url(r'^home$', views.home, name='home'),

    ## Courses relatedstuff
    url(r'^courses$', views.view_courses, name='view_course'),
    url(r'^courses/add$', views.add_courses, name='add_course'),
    url(r'^courses/(?P<pk>\d+)/$', views.course_detail, name='course_detail'),

    # Feedback related stuff
    url(r'^feedback/add/(?P<course_id>\d+)/$',
        views.add_feedback,
        name="add_feedback"),
    url(r'^feedback/view/(?P<pk>\d+)/$',
        views.view_feedback,
        name="view_feedback"),
    url(r'^feedback/add/$', views.add_feedback_all, name="add_feedback_all"),
    url(r'^feedback/view/$', views.view_feedback_all,
        name="view_feedback_all"),

    ## Assignments related stuff
    url(r'^assignments$', views.assigns, name='view_assignment'),
    url(r'^assignments/add$', views.add_assigns, name='add_assignment'),
    url(r'^assignments/view/(?P<pk>\d+)/$',
        views.view_assign,
        name='view_assign_info'),

	## Mobile API
	url(r'^api/login$', views.login_api, name='login_api'),
	url(r'^api/signout$', views.signout_api, name='signout_api'),
    url(r'^api/courses$', views.all_courses_api, name='courses_api'),
    url(r'^api/dates$', views.dates_api, name='dates_api'),

    ## Get course wise details
    url(r'^api/course_detail$',views.course_list_api, name="course_detail_api"),
    url(r'^api/course_deadlines$',views.course_deadlines_api, name="course_deadlines_api"),

    ## Feedback Form API
    url(r'^api/course_feedback_detail$',views.course_form_api, name="course_feedback_detail"),
    url(r'^api/submit_feedback_form$', views.submit_feedback_form, name="submit_feedback_form"),

    # Get assignment detail for some particular assignment
    url(r'^api/assignment_detail$',views.assignment_detail,name="assignment_detail"),

]


handler404 = 'website.views.handler404'

lab12/cs251project/django/website/models.py
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models

# Create your models here.

CHOICES = (
    ('ST', 'Student'),
    ('PR', 'Professor'),
    ('TA', 'Teaching Assistant'),
    ('AD', 'Admin'),
)

## Member type which specifies member type
class Member(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	fullname = models.CharField(max_length=30)
	# Member type
	token = models.TextField(null=True,blank=True,default="-1")
	mtype = models.CharField(choices=CHOICES, default="ST",max_length=25)
	
	def __str__(self):
		return self.fullname

## Course details
class Course(models.Model):
	name = models.TextField()
	members = models.ManyToManyField(Member,blank=True)
	# assignments are added as foreign keys
	semester = models.IntegerField()
	added = models.DateField(auto_now_add=True,auto_now=False)
	course_code = models.CharField(max_length=6)

	def __str__(self):
		return self.course_code
##############################################################################

QUESTION_TYPES = (
	('MCQ','Multiple Choice Question'),
	('SHORT','Short answer type Question'),
	('RATE','Rating Type Question'),
)

## Contains the feedback for the current course
class Feedback(models.Model): 
	name = models.TextField()
	deadline = models.DateTimeField(blank=False)
	course = models.ForeignKey(Course)
	students = models.ManyToManyField(Member,blank=True)

	def __str__(self):
		return self.name

	class Meta:
		ordering = ['-deadline']


## Feedback Questions and answers
class FeedbackQuestion(models.Model):
	question = models.TextField()
	feedback = models.ForeignKey(Feedback)
	q_type = models.CharField(choices=QUESTION_TYPES, default="RATE",max_length=5)

	def __str__(self):
		return self.question


## Answer type to question given by users
## Each question will have 5 instances of this connected to it.
## Each one will store the rating number and the votes given to it
class FeedbackRatingAnswer(models.Model):
	q = models.ForeignKey(FeedbackQuestion)
	rating = models.IntegerField(default=0)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.q.question

## Feedback Multi choice answer
## Each answer given through the app will increase its votes_count by 1
class FeedbackMCQChoice(models.Model):
	text = models.TextField()
	q = models.ForeignKey(FeedbackQuestion)
	votes_count = models.IntegerField(default=0)

	def __str__(self):
		return self.text

## Each short answer added will get inserted and will be stored in the answer to the feedback question
class FeedbackShortAnswer(models.Model):
	q = models.ForeignKey(FeedbackQuestion)
	text = models.TextField()

	def __str__(self):
		return self.text

##	Feedback form -> Questions
##	Question -> Rating / MCQ / Short Answer


###############################################################################
## Contains the assignment details for the current course
class Assignment(models.Model):
	name = models.TextField()
	description = models.TextField()
	deadline = models.DateTimeField(blank=False)
	course = models.ForeignKey(Course)

	def __str__(self):
		return self.name + " - " + self.course.course_code

	class Meta:
		ordering = ['-deadline']

lab12/cs251project/django/website/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, authenticate, login
from .models import *
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.core import serializers
import json
from urllib import request as urlreq
# Create your views here.
from datetime import datetime as dt
import datetime
# noinspection PyUnresolvedReferences
from ratelimit.decorators import ratelimit

## Show the main view
## More like index page
@ratelimit(key='ip', rate='100/h')
def signin(request):
    if request.method == "GET":
        user = request.user
        if user.is_authenticated():
            return HttpResponseRedirect(reverse('website:home'))

        return render(request, "signin.html")

    elif request.method == "POST":

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(username=username, password=password)
        if user is None:
            messages.add_message(request, messages.ERROR, 'Invalid Username/Password.')
            return render(request, 'signin.html')

        member = user.member
        if member.mtype == 'ST':
            messages.add_message(request, messages.ERROR, 'Student logins are not allowed.')
            return render(request, 'signin.html')

        login(request, user)
        return HttpResponseRedirect(reverse('website:home'))


## Signup view which takes data and creates the account
@ratelimit(key='ip', rate='100/h')
def signup(request):

    if request.method == "GET":
        return HttpResponseRedirect(reverse('website:signin'))
    elif request.method == "POST":
        try:
            fullname = request.POST['fullname']
            username = request.POST['sUsername']
            password = request.POST['sPassword']
            isProf = request.POST.get('prof')
        except:
            messages.add_message(request, messages.ERROR, 'Invalid details!')
            return HttpResponseRedirect(reverse('website:signin'))

        ## We have the data
        userexists = User.objects.filter(username=username)
        if len(userexists) != 0:
            messages.add_message(request, messages.ERROR, "Email already used. Please use a different email.")
            return HttpResponseRedirect(reverse('website:signin'))

        newuser = User.objects.create(username=username, email=username)
        newuser.set_password(password)
        newuser.save()

        if isProf == "on":
            mtype = "PR"
        else:
            mtype = "TA"

        newmember = Member.objects.create(
            user=newuser,
            fullname=fullname,
            mtype=mtype, )
        newmember.save()
        messages.add_message(request, messages.SUCCESS, 'Successfully registered! Now you can log in.')
        return HttpResponseRedirect(reverse('website:signin'))


## Add views for Home Page
## Will contain different stuff for Admins and TAs/Profs
@login_required
def home(request):
    ## Anon users are shooed away
    if request.user.is_anonymous():
        messages.add_message(request, messages.ERROR, 'Please login first!')
        return HttpResponseRedirect(reverse('website:signin'))

    if request.user.is_superuser:
        return HttpResponseRedirect('/admin')

    user = request.user
    member = get_object_or_404(Member, user=user)

    context = {'member': member}

    return render(request, 'home.html', context)


## Signout and return to homepage
def signout(request):
    logout(request)
    return HttpResponseRedirect(reverse('website:signin'))


## Complete Registration
## Completes facebook signup
@ratelimit(key='ip', rate='100/h')
def completeReg(request):

    if request.method == "POST":
        print(request)
        try:
            token = request.POST['access_token']
        except:
            messages.add_message(request, messages.ERROR, 'Invalid access.')
            return HttpResponseRedirect(reverse('website:home'))

        ## Token has been retrieved
        print(token)

        ## Use Facebook ID to store things
        url = "https://graph.facebook.com/v2.8/me?fields=first_name,middle_name,last_name&access_token="+token
        content = json.loads((urlreq.urlopen(url).read()).decode('utf-8'))

        print(content)

        ## if user exists, log in
        try:
            user = User.objects.filter(username=content['id'])
            if len(user) != 0:
                user = user[0]
                login(request,user)
                return HttpResponseRedirect(reverse('website:home'))


            context = {
                'fullname': content['first_name'] + " " + content['last_name'],
                'username': content['id'],
            }
            
        except:
            messages.add_message(request, messages.ERROR, 'Invalid access token!')
            return HttpResponseRedirect(reverse('website:home'))


        return render(request,'complete-reg.html',context)

    else:
        messages.add_message(request, messages.ERROR, 'Invalid details!')
        return HttpResponseRedirect(reverse('website:home'))


## Complete signup here
@ratelimit(key='ip', rate='100/h')
def complete_signup(request):

    if request.method == "POST":
        # response from form
        try:
            fullname = request.POST['fullname']
            fb_id = request.POST['username']
            username = request.POST['username']
            isProf = request.POST.get('prof')
        except:
            messages.add_message(request, messages.ERROR, 'Invalid details!')
            return HttpResponseRedirect(reverse('website:signin'))

        user = User.objects.filter(username=fb_id)
        if len(user) != 0:
            print(user)
            login(request,user)
            return HttpResponseRedirect(reverse('website:signin'))

        user = User.objects.create(username=fb_id)
        user.save()

        if isProf == "on":
            mtype = "PR"
        else:
            mtype = "TA"

        member = Member.objects.filter(user=user)
        if len(member) != 0:
            user.delete()
            messages.add_message(request, messages.ERROR, 'This user already exists! Try logging in!')
            return HttpResponseRedirect(reverse('website:signin'))

        member = Member.objects.create(
            user=user, fullname=fullname, mtype=mtype)
        member.save()
        messages.add_message(request, messages.SUCCESS, 'The account is successfully created.')
        return HttpResponseRedirect(reverse('website:home'))

    else:
        messages.add_message(request, messages.ERROR, 'Invalid access.')
        return HttpResponseRedirect(reverse('website:home'))


#######################################################################################
### Admin features
### View and add students
@login_required
def view_students(request):

    member = Member.objects.get(user=request.user)
    if member.mtype != "AD":
        return render(request, 'view_students.html',{
            'error':'Only admin(s) can view the list.'
        })

    students = Member.objects.filter(mtype="ST").order_by('fullname')
    context = {
        'students':students,
    }
    return render(request, 'view_students.html',context)

# Add student 
@login_required
def add_students(request):

    member = Member.objects.get(user=request.user)
    if member.mtype != "AD":
        return render(request, 'add_students.html',{
            'error':'Only admin(s) can view the list.',
            'hide':True
        })

    if request.method == "GET":
        return render(request, 'add_students.html')

    else:
        
        checkSingle = request.POST.get('fullname')

        ## Single register
        if checkSingle is not None:

            fullname = request.POST['fullname']
            username = request.POST['rollnumber'] + "@iitb.ac.in"
            test = User.objects.filter(username=username)
            if len(test) != 0:
                return render(request, 'add_students.html',{
                    'error':'This roll number already exists. Please try again.',
                })

            password = request.POST['password']
            u = User.objects.create(
                username=username,
                )

            u.set_password(password)
            u.save()

            m = Member.objects.create(
                user=u,
                fullname=fullname,
                mtype="ST",
                )

            messages.add_message(request, messages.SUCCESS, 'Successfully added student!')
            return HttpResponseRedirect(reverse('website:view_students'))

        else:
            try:
                print(request.FILES)
                studentdata = request.FILES['students']
                ## read data
                lines = studentdata.readlines()
                lines = list(map(lambda x: x.decode("utf-8"), lines))
                lines = list(map(lambda x: x[0:-1].split(','), lines))
                lines = list(map(lambda x: [x[0],x[1] + "@iitb.ac.in", x[2]], lines))

                for line in lines:
                    if len(line[2]) < 8:
                        messages.add_message(request, messages.ERROR, 'Password must be at least 8 characters long. Please check the file again.')
                        return HttpResponseRedirect(reverse('website:add_students'))
            except:
                messages.add_message(request, messages.ERROR, 'Incorrect format of submitted file!')
                return HttpResponseRedirect(reverse('website:add_students'))

            # Filter the line
            lines = list(filter(lambda x: len(User.objects.filter(username=x[1]))==0, lines))
            print(lines)
            print("\n\n\n\n")

lab12/cs251project/django/website/templates/course_detail.html
{% extends 'nav.html' %}

{% block title %} Course Details for {{course.code}} {% endblock %}

{% block content %}
	<div class="container">
	<br>
	<br>
	<br>
		{% if error %}
			<div class="center">
				{{error}}
			</div>
		{% else %}

			<h3>Course details for {{course.course_code}}</h3>
			<b>Course name</b>: {{course.name}} <br>
			<b>Semester</b>: {{course.semester}} <br>
			<b>Year</b>: {{course.added.year}} <br>
			<b>Students Enrolled</b>: {{students_enrolled}} <br>
			<b>Number of Teaching Assistants</b>: {{ta_count}} <br>
			<hr>
			{% if member.mtype == "AD" %}
			<b>Professor</b>: {{courseprof}} <br>
			{% endif %}

			
			<div class="row">
				<div class="col s12">
					<h5>Feedbacks</h5>
				</div>
				<div class="col s12">
					{% if member.mtype != "AD" %}<a href="{% url 'website:add_feedback' course.pk %}" class="btn green">Add Feedback</a>{% endif %}
				</div>
			</div>
			{% if feedbacks %}
					<table class="highlight">
						<thead>
							<th>Name</th>
							<th>Deadline</th>
							<th class="center">Accepting Responses</th>
							{% if member.mtype != "AD" %}
							<th class="center">View feedback details</th>
							{% endif %}
						</thead>

						<tbody>
						{% for feedback in feedbacks %}
							<tr>
								<td>{{feedback.name}}</td>
								<td>{{feedback.deadline | date:'d M, Y'}}</td>
								<td class="center">
									{% if feedback.deadline < now %}
										<i class="material-icons red-text">clear</i>
									{% else %}
										<i class="material-icons green-text">done</i>
									{% endif %}
								</td>
								{% if member.mtype != "AD" %}
								<td class="center">
								<a class="btn" href="{% url 'website:view_feedback' feedback.pk %}">View</a>
								</td>
								{% endif %}
							</tr>
						{% endfor %}
						</tbody>
					</table>
								
			{% else %}
				<p>Hurray, no feedbacks!</p>
			{% endif %}
			<br><hr>
			<br>
			<div class="row">
				<div class="col s12">
					<h5>Assignments</h5>
				</div>
				<div class="col s12">
				{% if member.mtype != "AD" %}<a href="{% url 'website:add_assignment' %}" class="btn green">Add Assignment</a>{% endif %}
				</div>	
			</div>		
			
			{% if assignments %}
				
				<table class="highlight">
					<thead>
						<th>Name</th>
						<th>Deadline</th>
						<th class="center">Accepting submissions</th>
						{% if member.mtype != "AD" %}
						<th class="center">View assignment details</th>
						{% endif %}
					</thead>

					<tbody>
					{% for assignment in assignments %}
						<tr>
							<td>{{assignment.name}}</td>
							<td>{{assignment.deadline | date:'d M, Y'}}</td>
							<td class="center">
								{% if assignment.deadline < now %}
									<i class="material-icons red-text">clear</i>
								{% else %}
									<i class="material-icons green-text">done</i>
								{% endif %}
							</td>
							{% if member.mtype != "AD" %}
							<td class="center"><a class="btn" href="{% url 'website:view_assign_info' assignment.pk %}">View</a></td>
							{% endif %}
						</tr>
					{% endfor %}
					</tbody>

				</table>

			{% else %}
				<p>Hurray, no assignments!</p>
			{% endif %}

		{% endif %}
		<br>
		<center><a class="waves-effect waves-light btn" href="{% url 'website:view_course' %}">Back</a></center>
	</div>
{% endblock %}

lab12/cs251project/django/website/templates/home.html
{% extends 'nav.html' %}

{% load staticfiles %}
{% block title %}
Home
{% endblock %}

{% block content %}
	<div class="container">
		<br>
		<br>
		<br>
    <center>
		Welcome, {{member.fullname}} <br>
		You are {{member.get_mtype_display}} <br> <br>
        {% if member.mtype == "AD" %}
        <img src="{% static 'images/access_granted.png' %}" width="600">
        {% else %}
            <img src="{% static 'images/prof.jpg' %}">
        {% endif %}
    </center>
		<hr>

		<!-- Add content here -->
		{% if member.mtype == "AD" %}
			<div class="row center">
				<div class="col s6">
					<a href="{% url 'website:add_course' %}" class="btn btn-block">Add Courses!</a>
				</div>
				<div class="col s6">
					<a href="{% url 'website:view_course' %}" class="btn btn-block">View Courses</a>
				</div>
			</div>
			<div class="row center">
				<div class="col s6">
					<a href="{% url 'website:view_students' %}" class="btn btn-block">View student list</a>
				</div>
				<div class="col s6">
					<a href="{% url 'website:add_students' %}" class="btn btn-block">Add student</a>
				</div>
			</div>
		{% else %}
            <div class="row center">
                    <div class="col s6 offset-m3">
					<a href="{% url 'website:view_course' %}" class="btn btn-block ">My Courses</a>
				    </div>
            </div>
			<div class="row center">
                <div class="col s6">
                    <a href="{% url 'website:view_assignment' %}" class="btn btn-block">View Assignments</a>
				</div>
                <div class="col s6">
                    <a href="{% url 'website:add_assignment' %}" class="btn btn-block">Add Assignments</a>
				</div>
			</div>

			<div class="row center">
				<div class="col s6">
					<a href="{% url 'website:view_feedback_all' %}" class="btn btn-block ">View Feedbacks</a>
				</div>
				<div class="col s6">
					<a href="{% url 'website:add_feedback_all' %}" class="btn btn-block ">Add Feedback</a>
				</div>
			</div>

		{% endif %}

	</div>
{% endblock %}

lab12/cs251project/django/website/templates/nav.html
{% extends 'base.html' %}



{% block navbar %}
    {% load staticfiles %}
<div class="navbar-fixed" style="z-index: 100">
<nav style="z-index: 100">
    <div class="nav-wrapper blue" style="z-index: 100">
      <a href="{% url 'website:home' %}" class="brand-logo">&nbsp;&nbsp;Feed'er</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
      	<li><a href="{% url 'website:home' %}">Home</a></li>       
        <li><a href="{% url 'website:signout' %}">Logout</a></li>       
      </ul>
    </div>
</nav>
</div>
{% endblock %}

lab12/cs251project/django/website/templates/view_assignments.html
{% extends 'nav.html' %}
{% load index %}

{% block title %}

    Assignments

{% endblock %}

{% block content %}
    {% if error == "Trespassers will be shot. Survivors will be shot again :P" %}
        <div class="row">
<div class="col s8 offset-m2">
    <h4 style="font-weight: 200; color: #f00;text-align: center">{{ error }}</h4>
        </div></div>
    {% else %}
    <div class="row">
<div class="col s8 offset-m2">
    <h3 class="center">Assignments</h3>
    <hr><br><br>
    {% if error %}
        <div class="row">
<div class="col s8 offset-m2">
    <h4 style="font-weight: 200; color: #f00;text-align: center">{{ error }}</h4>
        </div></div>
    {% else %}
    {% for assign in assigns %}
        <div class="row" style="text-align: center">
            <h5 style="color: #00b0ff;">{{ courses | index:forloop.counter0 }}</h5>
        </div>

        {% if  assign|length == 0 %}
            <div class="center">No assignments. Add one <a href="{% url 'website:add_assignment' %}">here.</a></div>
        {% else %}
        <div>
            <table class="highlight">
                <thead>
                    <th>Name</th>
                    <th>Deadline</th>
                    <th class="center">Accepting Submissions</th>
                    <th class="center">View</th>
                </thead>

                <tbody>
                    {% for foo in assign %}
                        <tr>
                            <td>{{ foo.name }}</td>
                            <td>{{ foo.deadline|date }}</td>
                            <td class="center">{% if foo.deadline < now %}
                                <i class="material-icons red-text">clear</i>
                                {% else %}
                                <i class="material-icons green-text">done</i>
                                {% endif %}
                            </td>
                            <td><a class="btn btn-block" href="{% url 'website:view_assign_info' foo.pk %}">See Description</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
           <!--  <div class="col s12 m6">
            <div class="card horizontal">
              <div class="card-stacked">
                <div class="card-content">
                  <h5 class="center">{{ foo.name }}</h5><br>
                    <p class="center">{{ foo.deadline|date }}</p>
                </div>
                <div class="card-action center">
                </div>
              </div>
            </div>
            </div> -->
        </div>
        {% endif %}
        <br>
        <hr style="width: 100%">
        <br>
    {% endfor %}
        {% endif %}
<center>
    <a class="waves-effect waves-light btn" href="{% url 'website:add_assignment' %}">Add Assignment</a>
    </center>
</div>
    </div>
    {% endif %}
{% endblock %}

lab12/cs251project/django/website/templates/view_courses.html
{%  extends 'nav.html' %}

{% block title %}
View Courses
{% endblock %}

{%  block content %}
	{% load index %}
	<div class="container">
		{% if error %}
		<br>
		{{error}}
		{% else %}

			{% if all_courses %}
				<h3 class="center">View all courses</h3>
				{% if member.mtype == "AD" %}
					<!-- Admin format -->
					<table class="highlight">
						<thead>
							<th>Course Name</th>
							<th>Course Code</th>
							<th>Professor</th>
							<th>Semester</th>
							<th>Year</th>
							<th>View details</th>
						</thead>

						<tbody>
							{% for course in all_courses %}
							<tr>
								<td>{{course.name}}</td>
								<td>{{course.course_code}}</td>
								<td>{{ profs|index:forloop.counter0 }}</td>
								<td>{%  if course.semester == 1 %}
                                            Fall
                                       {% elif course.semester == 2 %}
                                            Spring
                                       {% else %}
                                            Summer
                                       {% endif %}</td>
								<td>{{course.added.year}}</td>
								<td><a href="{% url 'website:course_detail' course.pk %}" class="btn waves-effect">View</a></td>
							</tr>
							{% endfor %}
						</tbody>
					</table>


				{% else %}
					<!-- Professor/TA side -->
					<br>
					<p class="center"><b>{{member.fullname}}</b></p>
					<table class="highlight">
						<thead>
							<th>Course Name</th>
							<th>Course Code</th>
							<th>Semester</th>
							<th>Year</th>
							<th>View details</th>
						</thead>

						<tbody>
							{% for course in all_courses %}
							<tr>
								<td>{{course.name}}</td>
								<td>{{course.course_code}}</td>
								<td>{%  if course.semester == 1 %}
                                            Fall
                                       {% elif course.semester == 2 %}
                                            Spring
                                       {% else %}
                                            Summer
                                       {% endif %}</td>
								<td>{{course.added.year}}</td>
								<td><a href="{% url 'website:course_detail' course.pk %}" class="btn waves-effect">View</a></td>
							</tr>
							{% endfor %}
						</tbody>
					</table>

				{% endif %}
			
			{% else %}
				<div class="row">
<div class="col s8 offset-m2">
    <h4 style="font-weight: 200; color: #f00;text-align: center">No courses available now.</h4>
        </div></div>
			{% endif %}

		{% endif %}
	</div>
{% endblock %}

lab12/cs251project/django/website/templates/view_feedback_all.html
{% extends 'nav.html' %}
{% load index %}
{% block title %} Feedback details for {{member.fullname}} {% endblock %}

{% block content %}
	<div class="container">
	<br>
	<br>
	<br>
		{% if error %}
			<div class="row">
<div class="col s8 offset-m2">
    <h4 style="font-weight: 200; color: #f00;text-align: center">{{ error }}</h4>
        </div></div>
		{% else %}
			<h5 class="center">All feedbacks for {{member.fullname}}</h5>
			{% for c in course_data %}
				<br>
				<div class="card-panel hoverable">
					<h5 class="center">{{c.course.name}} - {{c.course.course_code}}</h5>
					{% if c.feedbacks %}
						<table class="highlight">
							<thead>
								<th>Feedback Name</th>
								<th>Deadline</th>
								<th class="center">Accepting responses</th>
								<th class="center">View Details</th>
							</thead>

							<tbody>
								{% for feedback in c.feedbacks %}
									<tr>
										<td>{{feedback.name}}</td>
										<td>{{feedback.deadline | date:'j M, Y'}}</td>
										<td class="center">{% if feedback.deadline < now %} <i class="material-icons red-text">clear</i> {% else %} <i class="material-icons green-text">done</i> {% endif %}</td>
										<td><a href="{% url 'website:view_feedback' feedback.pk %}" class="btn btn-block">View</a></td>
									</tr>
								{% endfor %}
							</tbody>
						</table>
					{% else %} <br>
					Sorry, no feedback forms for this course. Add one <a href="{% url 'website:add_feedback_all' %}">here.</a>
					{% endif %}
				</div>
			{% endfor %}
		{% endif %}
	</div>
{% endblock %}

lab12/cs251project/django/website/templates/view_students.html
{% extends 'nav.html' %}
{% block title %}View Student Details{% endblock %}

{% block content %}
<!-- Block begins here -->

	<div class="container">
		<br>
		<div class="messages center">
		    {% if messages %}
		        {% for message in messages %}
		            {% if 'error' in message.tags %}
		            <p class="red-text">{{message}}</p>
		            {% elif 'success' in message.tags %}
		            <p class="green-text">{{message}}</p>
		            {% endif %}
		        {% endfor %}
		    {% endif %}
		</div>

		{% if error %}
			<h5 class="center red-text">{{error}}</h5>
		{% else %}
			<!-- Do your thing here -->
			{% if students %}
			<!-- Add table -->
			<br>
			<h5 class="center">Students List</h5>
			<div class="row">
				<div class="col s8"></div>
				<div class="col s4 right-align">
					<a href="{% url 'website:add_students' %}" class="btn green">Add a student!</a>
				</div>
			</div>
			<table class="highlight">
				<thead>
					<tr>
						<th>Sl. No.</th>
						<th>Name</th>
						<th>Email</th>
						<th class="center" width="25%">Number of courses taken</th>
					</tr>
				</thead>

				<tbody>
					{% for student in students %}
					<tr>
						<td>{{forloop.counter}}</td>
						<td>{{student.fullname}} </td>
						<td>{{student.user.username}} </td>
						<td class="center">{{student.course_set.all.count}} </td>
					</tr>
					{% endfor %}
				</tbody>

			</table>
			{% else %}
			<b>There are no registered students. Register one <a href="{% url 'website:add_students' %}">here.</a></b>
			{% endif %}
		{% endif %}
	</div>

{% endblock %}